#!/usr/bin/env node
// prd-phase.mjs — deterministic support for adding a PHASE to an existing PRD tree.
//
// A project does not stop at Gate 2. Phase 2 gets its own PRD *document*
// (docs/PRD-02-<name>.md), but it must decompose into the SAME docs/prd/ tree:
// dag-scan.mjs, dag-report.mjs and /start-all each take exactly ONE root, and a
// cross-phase `blocked_by` only resolves inside one graph. Splitting the tree would
// break the single global DAG that issue #71 exists to provide, and a dangling
// cross-tree dependency is a hard failure by design (catalog issue #112).
//
// Two verbs. Both are deterministic on purpose: the Architect is handed DATA, not a
// prose instruction to be careful, because prose-only role rules are a recorded
// failure mode of this pattern (README §4, orchestrator role leakage).
//
//   context [prd-root] [--prd <prd-file>]
//     What already exists, so a later phase cannot collide with an earlier one.
//     PHASE-CONTEXT-JSON: {root, phase, append, modules:[{dir,prefix,name,tickets:[id]}],
//                          nextPrefix, usedIds:[], existingFiles:[], planFile}
//     A missing or module-less root is phase 1 — reported, NOT an error, because that
//     is the ordinary first run.
//
//   check [prd-root] [--redo]
//     The freeze rule, enforced against git: under <prd-root>, files that ALREADY
//     EXIST may not be modified or deleted — only additions are allowed. Delivered
//     tickets' issues are closed and those files are the historical record of what was
//     built; rewriting them falsifies it. Adding a NEW ticket to an existing module is
//     fine, which is why the rule is per-file and not per-directory.
//     FREEZE-CHECK-JSON: {checked, reason?, violations:[{path,status}], additions:[]}
//     Exit 1 on any violation.
//
// `checked: false` is NOT a pass. Outside a git repo, or before the first commit,
// there is nothing to compare against, so the check cannot run — it exits 0 (a fresh
// phase-1 project must not be blocked) and the CALLER MUST RELAY the reason. Reporting
// an unrun check as a passed one is the exact failure class this repo keeps hitting
// (#83 vacuous test, #109 undeployed site).

import { execFileSync } from 'node:child_process'
import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

// `NN-name`. Prefixes 90-99 are RESERVED — the nightly sweep writes 99-nightly — so
// they never advance nextPrefix; otherwise one nightly run would push phase 3 to 100.
const MODULE_RE = /^(\d{2,})-(.+)$/
const RESERVED_FROM = 90

// dag.html is generated by dag-report.mjs on every breakdown, so it is expected to
// change and is exempt from the freeze rule. Nothing else under the root is.
const REGENERATED = /(^|\/)dag\.html$/

const argv = process.argv.slice(2)
const verb = argv[0]
const REDO = argv.includes('--redo')

const flagVal = (name) => {
  const i = argv.indexOf(name)
  return i !== -1 ? argv[i + 1] || '' : ''
}

const positional = []
for (let i = 1; i < argv.length; i++) {
  if (argv[i] === '--prd') { i++; continue }
  if (argv[i].startsWith('--')) continue
  positional.push(argv[i])
}
const root = (positional[0] || 'docs/prd').replaceAll('\\', '/').replace(/\/$/, '')

if (verb !== 'context' && verb !== 'check') {
  console.error('usage: node prd-phase.mjs <context|check> [prd-root] [--prd <prd-file>] [--redo]')
  process.exit(1)
}

// docs/PRD.md -> breakdown-plan.md   (phase 1 keeps the historical name)
// docs/PRD-02-billing.md -> breakdown-plan-02-billing.md
// Deterministic so the command never has to invent a filename, and so phase 1's
// module-split rationale is not clobbered by phase 2 (it was, before #112).
function planFileFor(prdPath) {
  const base = String(prdPath || '').replaceAll('\\', '/').split('/').pop().replace(/\.md$/i, '')
  const rest = base.replace(/^prd/i, '').replace(/^[-_\s]+/, '')
  const slug = rest.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')
  return slug ? `breakdown-plan-${slug}.md` : 'breakdown-plan.md'
}

const stripQuotes = (v) => {
  const s = v.trim()
  const m = s.match(/^(['"])([\s\S]*)\1$/)
  return m ? m[2] : s
}

function scanModules(dir) {
  if (!existsSync(dir)) return []
  const out = []
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (!e.isDirectory()) continue
    const m = e.name.match(MODULE_RE)
    if (!m) continue
    const tdir = join(dir, e.name, 'tickets')
    const tickets = []
    if (existsSync(tdir)) {
      for (const f of readdirSync(tdir).filter((n) => n.endsWith('.md')).sort()) {
        const text = readFileSync(join(tdir, f), 'utf8').replace(/^﻿/, '')
        const fm = (text.match(/^---\r?\n([\s\S]*?)\r?\n---/) || [])[1] || ''
        const idm = fm.match(/^id\s*:\s*(.+)$/m)
        if (idm) tickets.push(stripQuotes(idm[1]))
      }
    }
    out.push({ dir: e.name, prefix: m[1], name: m[2], tickets })
  }
  return out.sort((a, b) => a.dir.localeCompare(b.dir))
}

function* walk(dir) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const f = join(dir, e.name)
    if (e.isDirectory()) yield* walk(f)
    else yield f.replaceAll('\\', '/')
  }
}

if (verb === 'context') {
  const modules = scanModules(root)
  const planFile = planFileFor(flagVal('--prd') || 'docs/PRD.md')

  const advancing = modules.map((m) => Number(m.prefix)).filter((n) => Number.isFinite(n) && n < RESERVED_FROM)
  const width = Math.max(2, ...modules.map((m) => m.prefix.length), 2)
  const nextPrefix = String(advancing.length ? Math.max(...advancing) + 1 : 0).padStart(width, '0')

  const usedIds = [...new Set(modules.flatMap((m) => m.tickets))].sort()
  const existingFiles = existsSync(root)
    ? [...walk(root)].map((f) => f.slice(root.length + 1)).filter((f) => !REGENERATED.test(f)).sort()
    : []

  const append = modules.length > 0
  const payload = {
    root,
    phase: modules.length ? modules.length + 1 : 1, // advisory label, not an index
    append,
    modules,
    nextPrefix,
    usedIds,
    existingFiles,
    planFile,
  }

  console.log(
    append
      ? `${root}: ${modules.length} existing module(s), ${usedIds.length} ticket id(s) in use — APPEND mode.`
      : `${root}: no modules yet — first decomposition.`
  )
  console.log(`next module prefix: ${nextPrefix}   breakdown plan: ${root}/${planFile}`)
  if (append) console.log(`frozen (existing, must not be modified or deleted): ${existingFiles.length} file(s)`)
  console.log('PHASE-CONTEXT-JSON: ' + JSON.stringify(payload))
  process.exit(0)
}

// ---- check ----
const emit = (payload, code) => {
  console.log('FREEZE-CHECK-JSON: ' + JSON.stringify(payload))
  process.exit(code)
}

if (REDO) {
  console.log('freeze check bypassed by --redo — existing files under ' + root + ' MAY be rewritten.')
  emit({ checked: false, reason: '--redo (freeze intentionally bypassed)', violations: [], additions: [] }, 0)
}

const git = (args) => execFileSync('git', args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] })

try {
  git(['rev-parse', '--is-inside-work-tree'])
} catch {
  console.log('not a git repository — nothing to compare against, freeze NOT checked.')
  emit({ checked: false, reason: 'not a git repository', violations: [], additions: [] }, 0)
}
try {
  git(['rev-parse', '--verify', 'HEAD'])
} catch {
  console.log('no commits yet — every file is new, freeze NOT checked.')
  emit({ checked: false, reason: 'no commits yet', violations: [], additions: [] }, 0)
}

// `-uall` is load-bearing here for the same reason it is in deliver-ticket.mjs (#83):
// porcelain defaults to `-unormal`, which collapses an entirely-untracked directory to
// one entry — a brand-new module would be reported as a single path instead of its
// files, making the additions list useless for review.
const status = git(['status', '--porcelain', '-uall', '--', root])

const violations = []
const additions = []
for (const line of status.split('\n')) {
  if (!line.trim()) continue
  const xy = line.slice(0, 2)
  let path = line.slice(3)
  if (xy[0] === 'R' || xy[0] === 'C') path = path.split(' -> ').pop()
  path = path.trim().replace(/^"|"$/g, '').replaceAll('\\', '/')
  if (REGENERATED.test(path)) continue
  if (xy === '??' || xy[0] === 'A') { additions.push(path); continue }
  violations.push({ path, status: xy })
}

for (const v of violations) console.error(`x frozen file changed (${v.status.trim() || 'modified'}): ${v.path}`)
console.log(
  violations.length
    ? `FREEZE VIOLATION: ${violations.length} pre-existing file(s) under ${root} were modified or deleted. A delivered ticket is the record of what was built — change spec by ADDING a ticket, or re-run with --redo if this decomposition was never delivered.`
    : `freeze ok: ${additions.length} addition(s) under ${root}, no pre-existing file modified or deleted.`
)
emit({ checked: true, violations, additions }, violations.length ? 1 : 0)
